### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by WickyNilliams** [SanderSpies/react-material#3]
- [ ] Need to implement a base set of components 
- [ ] Properly implement the "theming" of the components
- [ ] Should work in IE8 whereby the functionality should not be broken
- [ ] Properly handle mobile interfaces with proper touch support
- [ ] Use Google Closure Compiler Advanced Mode for bragging rights
